name: angular_flatpickr
description: AngularDart port of flatpickr (javascript date/time picker).
version: 0.0.1
homepage: https://github.com/alexd1971/angular_flatpickr
author: Aleksey Danilevskiy <alexey.danilevsky@gmail.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  angular: '>=4.0.0 <5.0.0'
  angular_forms: '>=1.0.0 < 2.0.0'
  js: '>=0.6.1 <0.7.0'

dev_dependencies:
  angular_test: '>=1.0.0 <2.0.0'
  pageloader: '>=2.2.6 <2.3.0'
  test: '>=0.12.0 <0.13.0'

transformers:
  - angular:
      entry_points:
        - test/**_test.dart
  - test/pub_serve:
      $include: test/**_test.dart